### PR TITLE
[ES-1131459] Fix multiple Statefulsets down

### PR DESCRIPTION
**Pull request by yuchen-db**
see https://databricks.slack.com/archives/C02JU4CM6K0/p1715797633010659

### CODE REVIEW

**Comment by christopherzli** [comment]
lgtm assuming if you have tested thouroughly

**Review by christopherzli — APPROVED** [review]

**Review by jnyi — COMMENTED** [review]
is it possible to add some unit tests, I recall @christopherzli mentioned this repo can support a local KIND simulation. One thing to verify: this change can work properly if a statefulset replicas increase/decrease

**Review by hczhu-db — APPROVED** [review]

**Comment by yuchen-db** [comment]
need some time to test this

**Comment by jnyi** [comment]
> need some time to test this

yep, i can see linter and integration tests are failing now, please make them pass.

**Pull request closed without merging**
